version: "3.8"

services:
  app:
    image: docker-nextjs
    ports: 
    - 3001:3001
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
      # - ./pages:/app/pages
      # - ./public:/app/public
      # - ./styles:/app/styles
      # - ./hooks:app/hooks
      # - ./components:app/components
      # - ./packages/landingpage:/usr/src/app
      # - /usr/src/app/node_modules
      # - /usr/src/app/.next